language: swift
osx_image: xcode10
xcode_workspace: BlueOwl.xcworkspace
xcode_scheme: BlueOwl
env: XCODE_DESNITATION='platform=iOS Simulator,name=iPhone XS'
git:
  depth: false
install: skip
cache:
  directories:
    - DerivedData
script:
  - set -o pipefail && xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$XCODE_DESNITATION" -derivedDataPath DerivedData | xcpretty -f `xcpretty-travis-formatter`
after_success:
  - bash <(curl -s 'https://codecov.io/bash') -Z -J '^[^P].*Owl$' -X gcov -X fix -D DerivedData
