language: objective-c
osx_image: xcode9.4
xcode_workspace: BlueOwl.xcworkspace
xcode_scheme: BlueOwl
xcode_sdk: iphonesimulator11.4
env: XCODE_DESNITATION='platform=iOS Simulator,name=iPhone X'
git:
  depth: false
cache:
  cocoapods: true
  directories:
    - DerivedData
bundler_args: --no-deployment
script:
  - set -o pipefail && xcodebuild test -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" -destination "$XCODE_DESNITATION" -derivedDataPath DerivedData | xcpretty -f `xcpretty-travis-formatter`
after_success:
  - bash <(curl -s 'https://codecov.io/bash') -Z -J '^BlueOwl$' -X gcov -X fix
